### ISSUE TITLE
escaped quote problem?

### ISSUE THREAD

**Issue by bradleyjeck** [diogosmendonca/ApacheLogProcessor#1]
Thanks for publishing this package -- very handy.  In reading my log file using the defaults, it threw an error 

read.apache.log( "path2myLog") 

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 798 did not have 10 elements

line 798 is: 

12.34.56.78 - - [04/Sep/2016:20:40:34 -0700] "GET /xmlrpc.php HTTP/1.1" 405 42 "http://www.bradeck.net/xmlrpc.php" "\"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0\""

Should I call with a special argument?

**Comment by diogosmendonca** [comment]
Hello Bradley,

It seens that user agent field has quotes inside, to prevent read error use the parameter prevent_quotes_inside_url = TRUE. We will change this parameter name to prevent_quotes_inside_field because it prevents quotes not only inside URLs but all fields.

Tks for the feedback.

Diogo.

**Comment by bradleyjeck** [comment]
Thanks Diogo, that works. 

Other ideas for the parameter name :  "allow_quotes_in_fields" or "fields_have_quotes"

Cheers, 

Brad
