### ISSUE TITLE
webreadr

### ISSUE THREAD

**Issue by hrbrmstr** [diogosmendonca/ApacheLogProcessor#2]
just making sure you know abt `webreadr` — https://cran.r-project.org/web/packages/webreadr/

i do understand that your package has some extra functionality, but `webreadr` may be useful given that it has some serious speed improvements due to some ops being at C++ level.

**Comment by diogosmendonca** [comment]
Thank you for the advice. I know webreadr package and its better performance due to C++ implementation. ApacheLogProcessor first version is previous than webreadr, and since I didn’t have time to refactor the package to C or C++ it's still in R. I developed this package for use in my D.Sc. research about defects in web applications. I shared it because there was no other one in CRAN in 2015. I add extra functionalities in the package as I need them in research. This year I will add some additional features to the package, such as read NGiNX logs and parse more error logs. I will consider performing the refactoring to C or C++ this year, since it may help more people than me.

**Comment by hrbrmstr** [comment]
👍 

Also, I'm not sure if you're familiar with Apache Drill, but it can also be used to handle at-scale (even on a single-workstation) processing of these types of logs. It has a built-in web log parser and this plugin makes almost any log file usable: https://github.com/cgivre/drill-logfile2

I mention that since the `sergeant` package enables `dplyr`-like access to Apache Drill and I use the log file reading capabilities quite a bit.

**Comment by diogosmendonca** [comment]
Closing, this is not an issue.
